---
- name: Create VM with QEMU
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create disk from raw base image
      ansible.builtin.command: >
        cp {{ item.image }} /tmp/molecule-{{ item.name }}.raw
      args:
        creates: "/tmp/molecule-{{ item.name }}.raw"
      loop: "{{ molecule_yml.platforms }}"

    - name: Resize raw disk
      ansible.builtin.command: >
        qemu-img resize /tmp/molecule-{{ item.name }}.raw {{ item.disk_size | default('20G') }}
      loop: "{{ molecule_yml.platforms }}"

    - name: Create cloud-init directory
      ansible.builtin.file:
        path: "/tmp/cloud-init-{{ item.name }}"
        state: directory
        mode: '0755'
      loop: "{{ molecule_yml.platforms }}"

    - name: Create cloud-init user-data
      ansible.builtin.copy:
        content: |
          #cloud-config
          users:
            - name: {{ item.ssh_user | default('ubuntu') }}
              sudo: ALL=(ALL) NOPASSWD:ALL
              shell: /bin/bash
              ssh_authorized_keys:
                - {{ lookup('file', (item.ssh_key | default('~/.ssh/id_rsa')) ~ '.pub') }}
          runcmd:
            - systemctl disable unattended-upgrades || true
            - systemctl stop unattended-upgrades || true
        dest: "/tmp/cloud-init-{{ item.name }}/user-data"
        mode: '0644'
      loop: "{{ molecule_yml.platforms }}"

    - name: Create cloud-init meta-data
      ansible.builtin.copy:
        content: |
          instance-id: {{ item.name }}
          local-hostname: {{ item.name }}
        dest: "/tmp/cloud-init-{{ item.name }}/meta-data"
        mode: '0644'
      loop: "{{ molecule_yml.platforms }}"

    - name: Create cloud-init ISO
      ansible.builtin.command: >
        genisoimage -output /tmp/cloud-init-{{ item.name }}.iso
        -volid cidata -joliet -rock /tmp/cloud-init-{{ item.name }}/
      args:
        creates: "/tmp/cloud-init-{{ item.name }}.iso"
      loop: "{{ molecule_yml.platforms }}"

    - name: Check if VM is already running
      ansible.builtin.shell: |
        if [ -f /tmp/qemu-{{ item.name }}.pid ]; then
          if ps -p $(cat /tmp/qemu-{{ item.name }}.pid) > /dev/null 2>&1; then
            echo "running"
          else
            rm -f /tmp/qemu-{{ item.name }}.pid
            echo "not running"
          fi
        else
          echo "not running"
        fi
      register: vm_status
      loop: "{{ molecule_yml.platforms }}"

    - name: Start QEMU VM
      ansible.builtin.shell: |
        qemu-system-x86_64 \
          -name {{ item.item.name }} \
          -m {{ item.item.memory }} \
          -smp {{ item.item.cpus }} \
          -drive file=/tmp/molecule-{{ item.item.name }}.raw,format=raw,if=none,id=disk0,cache=unsafe,aio=threads \
          -device virtio-blk-pci,drive=disk0 \
          -cdrom /tmp/cloud-init-{{ item.item.name }}.iso \
          -netdev user,id=net0,hostfwd=tcp::{{ item.item.ssh_port }}-:22 \
          -device virtio-net-pci,netdev=net0 \
          -enable-kvm \
          -cpu host \
          -daemonize \
          -display none \
          -pidfile /tmp/qemu-{{ item.item.name }}.pid
      when: item.stdout == "not running"
      loop: "{{ vm_status.results }}"

    - name: Wait for SSH
      ansible.builtin.wait_for:
        host: 127.0.0.1
        port: "{{ item.ssh_port | default(2222) }}"
        timeout: 120
      loop: "{{ molecule_yml.platforms }}"

    - name: Create molecule instance config
      ansible.builtin.copy:
        content: |
          {% for item in molecule_yml.platforms %}
          - address: "127.0.0.1"
            identity_file: "{{ item.ssh_key | default('~/.ssh/id_rsa') }}"
            instance: "{{ item.name }}"
            port: "{{ item.ssh_port | default(2222) }}"
            user: "{{ item.ssh_user | default('ubuntu') }}"
            ssh_extra_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
          {% endfor %}
        dest: "{{ molecule_instance_config }}"
        mode: '0644'

    - name: Wait for cloud-init to finish
      ansible.builtin.pause:
        seconds: 30